const $=s=>document.querySelector(s), app=$('#app'), dialog=$('#modal');
const PAGES_BASE='https://zjwzkongqc.github.io/applications-mentioned-by-the-user-appshot/';
const SERVICE_BASE='https://tennis-dazi-club-2026.divine-seal-5110.chatgpt.site';
const config=window.TENNIS_CONFIG||{},apiBase=config.apiBaseUrl||location.origin;
const appBase=config.pageBaseUrl||`${location.origin}/`,remoteApi=new URL(apiBase).origin!==location.origin;
const sessionKey=`tennis-club:member:${apiBase}:${appBase}`,linkKey=sessionKey+':link';
const hashParams=new URLSearchParams(location.hash.slice(1)),validToken=x=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
function readSession(invite){try{return localStorage.getItem(sessionKey+':group:'+invite)||localStorage.getItem(sessionKey);}catch{return null;}}
let savedSession=readSession(hashParams.get('g'));
const state={invite:hashParams.get('g'),board:null,tab:'feed',avatars:new Map(),error:null,session:validToken(savedSession)?savedSession:null,linkIntent:!remoteApi&&hashParams.get('connect')==='pages'&&validToken(hashParams.get('state'))?hashParams.get('state'):null,linkShown:false};
function rememberSession(token,invite=state.invite){if(!validToken(token))throw new Error('名片连接没有完成，请重新进入。');state.session=token;try{if(validToken(invite))localStorage.setItem(sessionKey+':group:'+invite,token);if(!localStorage.getItem(sessionKey))localStorage.setItem(sessionKey,token);}catch{toast('当前浏览器无法记住名片，请保留这个页面。');}}
if(remoteApi&&hashParams.has('session')){
  let pending;try{pending=JSON.parse(sessionStorage.getItem(linkKey)||'null');sessionStorage.removeItem(linkKey);}catch{}
  const transferred=hashParams.get('session');
  if(validToken(transferred)&&pending?.nonce===hashParams.get('state')&&pending?.invite===state.invite&&Date.now()-pending.created<600000&&Date.now()>=pending.created)rememberSession(transferred);
  else state.linkFailed=true;
  history.replaceState(null,'',`${appBase}${state.invite?'#g='+encodeURIComponent(state.invite):''}`);
}
function apiFetch(path,options={}){const headers=new Headers(options.headers);if(state.invite)headers.set('Authorization',`Bearer ${state.invite}`);if(remoteApi&&state.session)headers.set('X-Tennis-Session',state.session);return fetch(new URL(path,apiBase),{...options,headers,credentials:remoteApi?'omit':'same-origin'});}
function beginPagesLink(){const nonce=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');try{sessionStorage.setItem(linkKey,JSON.stringify({nonce,invite:state.invite,created:Date.now()}));}catch{toast('这个浏览器无法连接原名片，请使用原页面。');return;}location.assign(`${SERVICE_BASE}/#g=${encodeURIComponent(state.invite)}&connect=pages&state=${nonce}`);}
function showPagesLink(){if(!state.linkIntent||state.linkShown)return;state.linkShown=true;const m=me();modal(m?'继续使用原来的名片':'原页面没有找到你的名片',m?`<p>把 <strong>${esc(m.nickname)}</strong> 的名片连接到 GitHub 页面。你的训练记录、群主身份和头像会继续保留。</p><div class="form-actions"><button class="secondary" data-action="pages-return">返回 GitHub</button><button class="primary" data-action="confirm-pages-link">连接这张名片</button></div>`:`<p>请在建立这张名片的微信或浏览器中打开。也可以返回 GitHub 页面，用新昵称加入。</p><div class="form-actions"><button class="primary" data-action="pages-return">返回 GitHub</button></div>`);}

const moods=['手感在线','快乐拉球','认真练球','虽败犹荣','饭后消食'];
const icons={feed:'<path d="M8 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2h-3M9 2h6v4H9zM7 11h10M7 16h7"/>',members:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/><circle cx="9" cy="7" r="4"/>',culture:'<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/><path d="M8 10h8M8 14h5"/>',my:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',plus:'<path d="M12 5v14M5 12h14"/>',share:'<path d="M12 16V3M7 8l5-5 5 5M5 13v7h14v-7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',refresh:'<path d="M20 7a9 9 0 1 0 1 8M20 3v5h-5"/>'};
function icon(name){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.feed}</svg>`;}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function hours(m){return String(Math.round(Number(m)/60*10)/10);}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function day(s){const [y,m,d]=s.split('-');return `${Number(m)}月${Number(d)}日`;}
function me(){return state.board?.members.find(m=>m.id===state.board.me);}
function member(id){return state.board?.members.find(m=>m.id===id);}
function findRecord(id){return Growth.model.data?.records.find(r=>r.id===id)||state.board?.records.find(r=>r.id===id);}
function avatar(m,large=false){const url=m&&state.avatars.get(m.id)?.url;return `<span class="avatar ${large?'large':''}" data-tone="${m?m.id.charCodeAt(0)%4:0}" ${m?.id?`data-avatar="${esc(m.id)}"`:''}>${url?`<img src="${esc(url)}" alt="${esc(m.nickname)}的头像">`:esc(m?.nickname?.slice(0,1)||'球')}</span>`;}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),3200);}
async function request(path,method='GET',data){const headers={};if(state.invite)headers.Authorization=`Bearer ${state.invite}`;if(data)headers['Content-Type']='application/json';let response;try{response=await apiFetch(path,{method,headers,body:data?JSON.stringify(data):undefined});}catch{throw new Error('网络暂时不通，填写的内容还在，请重试。');}const result=await response.json().catch(()=>({error:'暂时没有收到回复，请重试。'}));if(!response.ok)throw new Error(result.error||'保存失败，请重试。');if(remoteApi&&result.sessionToken)rememberSession(result.sessionToken,result.invite||state.invite);return result;}
async function load({quiet=false}={}){try{state.board=await request('/api/board');if(remoteApi&&state.board.me&&state.session)rememberSession(state.session);if(state.board.me)await Growth.load();else Growth.reset();state.error=null;document.title=`${state.board.club.name} · 网球小本本`;render();loadAvatars();showPagesLink();}catch(e){state.error=e.message;if(!quiet||state.board)render();}}
async function loadAvatars(){for(const m of state.board?.members||[]){if(!m.hasAvatar)continue;if(state.avatars.get(m.id)?.version===m.avatarVersion)continue;try{const r=await apiFetch(`/api/avatar/${m.id}`);if(!r.ok)continue;const blob=await r.blob(),url=URL.createObjectURL(blob),old=state.avatars.get(m.id);if(old)URL.revokeObjectURL(old.url);state.avatars.set(m.id,{url,version:m.avatarVersion});document.querySelectorAll(`[data-avatar="${m.id}"]`).forEach(e=>{e.innerHTML=`<img src="${url}" alt="${esc(m.nickname)}的头像">`;});}catch{}}}
const tabs=[['feed','球场动态'],['members','球友名片'],['culture','群里那些梗'],['my','成长档案']];
function nav(){return tabs.map(([key,label])=>`<button class="nav-item ${state.tab===key?'active':''}" data-action="tab" data-tab="${key}" ${state.tab===key?'aria-current="page"':''}>${icon(key)}<span>${label}</span></button>`).join('');}
function stats(person){const b=state.board;return `<div class="stats"><div class="stat"><div class="stat-label">${icon('feed')}${person?'我的打球记录':'群里的打球记录'}</div><div class="stat-number">${person?person.record_count:b.totals.records}<small>次</small></div></div><div class="stat"><div class="stat-label">${icon('clock')}${person?'我的球场时光':'累计球场时光'}</div><div class="stat-number">${hours(person?person.minutes:b.totals.minutes)}<small>小时</small></div></div><div class="stat"><div class="stat-label">${icon('members')}${person?'我的球场徽章':'已加入的球友'}</div><div class="stat-number">${person?(Number(person.record_count)>=10?'10场':Number(person.record_count)>=5?'5场':Number(person.record_count)>=1?'首场':'待解锁'):b.members.length}<small>${person?'纪念':'位'}</small></div></div></div>`;}
function recordCard(r){const b=state.board,m=member(r.member_id),mine=r.member_id===b.me,reactions=b.cheers.filter(c=>c.record_id===r.id);return `<article class="record"><div class="record-head"><div class="identity">${avatar(m)}<div><strong>${esc(m?.nickname||r.nickname)}${mine?' <span class="optional">· 我</span>':''}</strong><small>${esc(r.mood)}</small></div></div><time class="record-date" datetime="${esc(r.play_date)}">${esc(r.play_date.slice(0,4))} / ${day(r.play_date)}</time></div><div class="record-tags"><span class="tag">${icon('clock')} ${r.minutes} 分钟</span>${r.venue?`<span class="tag">${esc(r.venue)}</span>`:''}<span class="tag mood">🎾 ${esc(r.mood)}</span></div>${r.note?`<p class="record-note">${esc(r.note)}</p>`:'<p class="record-note">又攒下了一场球场时光。</p>'}${r.partners?`<p class="record-partners">一起打球：${esc(r.partners)}</p>`:''}${Growth.recordDetails(r)}${Hexagon.recordChip(r)}<div class="record-bottom"><div class="cheers">${['👏','🔥','🎾'].map(e=>`<button class="cheer ${reactions.some(c=>c.member_id===b.me&&c.emoji===e)?'chosen':''}" data-action="cheer" data-id="${r.id}" data-emoji="${e}" aria-label="${e==='👏'?'鼓掌':e==='🔥'?'手感火热':'一起打球'}，${reactions.filter(c=>c.emoji===e).length} 人">${e} <span>${reactions.filter(c=>c.emoji===e).length||''}</span></button>`).join('')}</div>${mine?`<div class="record-tools"><button class="text-button" data-action="edit-record" data-id="${r.id}">编辑</button><button class="text-button danger" data-action="delete-record" data-id="${r.id}">删除</button></div>`:''}</div></article>`;}
function emptyRecord(personal=false){return `<div class="empty"><span class="empty-mark">🎾</span><h3>${personal?'你的故事，从这一场开始':'这里还差第一场球'}</h3><p>${personal?'记下打球时长和今天的手感，下次回看会很有意思。':'打了多久、和谁一起、有什么趣事？让群里的网球故事慢慢攒起来。'}</p><button class="primary" data-action="record">${icon('plus')}记一场球</button></div>`;}
function aside(){const b=state.board;return `<aside class="aside"><div class="club-card"><p class="eyebrow">OUR COURT, OUR CLUB</p><h3>${esc(b.club.slogan||'每一场球，都算数。')}</h3><p>胜负留在球场，快乐记在这里。<br>你的搭子、你的故事、你们的梗。</p><button class="primary lime" data-action="invite">${icon('share')}邀请群友一起记</button></div><div class="mini-card"><div class="section-heading"><h3>在这里的搭子</h3><button class="text-button" data-action="tab" data-tab="members">看全部</button></div><div class="mini-members">${b.members.slice(0,8).map(m=>avatar(m)).join('')}</div><p>${b.members.length} 位球友，慢慢打成一个圈。</p></div><p class="hint">用自己的昵称记自己的球，<br>让每一次挥拍都有个着落。</p></aside>`;}
function feed(){const b=state.board;return `<div class="page-heading"><div><p class="eyebrow">COURT NOTES / 群里的网球小本本</p><h1>${esc(b.club.name)}</h1><p class="subtext">看看大家最近打了什么球。</p></div><div class="heading-actions"><button class="primary" data-action="training">${icon('plus')}记录训练</button><button class="secondary" data-action="record">记一场球</button></div></div>${joinBanner()}${Growth.checkinBar()}${stats()}<div class="workspace"><section><div class="section-heading"><h2>最近的球场故事</h2><button class="text-button" data-action="refresh">${icon('refresh')}刷新</button></div><div class="feed">${b.records.length?b.records.map(recordCard).join(''):emptyRecord()}</div>${Number(b.totals.records)>500?'<p class="hint">这里展示最近 500 条记录，累计统计包含全部记录。</p>':''}</section>${aside()}</div>`;}
function joinBanner(){return !state.board.me?`<div class="join-banner"><div><strong>给自己一张球友名片</strong><p>取个群昵称，就能记录打球、给搭子鼓掌。</p></div><div><button class="primary" data-action="profile">加入这群搭子</button>${remoteApi?'<button class="text-button" data-action="link-pages">使用原页面的名片</button>':''}</div></div>`:'';}
function badge(m){return Number(m.record_count)>=10?'十场常客':Number(m.record_count)>=5?'球场熟面孔':Number(m.record_count)>=1?'首场留念':'刚刚入场';}
function members(){const b=state.board;return `<div class="page-heading"><div><p class="eyebrow">MEET THE CREW</p><h1>这一群，都是搭子。</h1><p class="subtext">${b.members.length} 位球友，每个人都有自己的球风。</p></div><button class="primary" data-action="${b.me?'profile':'profile'}">${icon('my')}${b.me?'编辑我的名片':'建立我的名片'}</button></div><div class="member-grid">${b.members.map(m=>`<article class="member-card"><div class="member-top">${avatar(m,true)}${Hexagon.badge(m)}</div><h3>${esc(m.nickname)}${m.id===b.me?' <span class="optional">· 我</span>':''}</h3><p class="bio">${esc(m.bio||'先打球，慢慢熟。')}</p>${Hexagon.memberSummary(m,true)}<div class="member-numbers"><div><strong>${m.record_count}</strong><span>场记录</span></div><div><strong>${hours(m.minutes)}</strong><span>小时</span></div></div></article>`).join('')}</div>`;}
function culture(){const b=state.board;return `<div class="page-heading"><div><p class="eyebrow">ONLY WE GET IT</p><h1>群里那些梗。</h1><p class="subtext">口头禅、球场名场面，懂的人自然懂。</p></div><button class="primary" data-action="culture">${icon('plus')}留下一句群内梗</button></div>${joinBanner()}${b.culture.length?`<div class="culture-grid">${b.culture.map(p=>`<article class="culture-card"><p class="culture-quote">“${esc(p.content)}”</p><div class="culture-credit"><div class="identity">${avatar(member(p.member_id))}<div><strong>${esc(member(p.member_id)?.nickname||p.nickname)}</strong><small>${day(p.created_at.slice(0,10))}</small></div></div>${p.member_id===b.me?`<button class="text-button danger" data-action="delete-culture" data-id="${p.id}">删除</button>`:''}</div></article>`).join('')}</div>`:'<div class="empty"><span class="empty-mark">💬</span><h3>只有你们懂的那一句</h3><p>还没有群内梗。把球场上的名场面、群里的口头禅留在这里。</p><button class="primary" data-action="culture">留下一句</button></div>'}`;}
function mine(){const m=me();if(!m)return `<div class="page-heading"><div><p class="eyebrow">MY COURT NOTES</p><h1>我的小本本</h1></div></div>${joinBanner()}<div class="empty"><span class="empty-mark">👋</span><h3>先让搭子认识你</h3><p>昵称、头像，再加一句你的球场宣言。</p><button class="primary" data-action="profile">建立球友名片</button></div>`;const records=state.board.records.filter(r=>r.member_id===m.id);return `<div class="page-heading"><div><p class="eyebrow">MY COURT NOTES</p><h1>我的小本本</h1><p class="subtext">每一次出门打球，都是一点小小的进步。</p></div><button class="primary" data-action="record">${icon('plus')}记一场球</button></div><div class="my-card"><div class="identity">${avatar(m,true)}<div><h2>${esc(m.nickname)}</h2><small>${esc(m.bio||'先打球，慢慢熟。')}</small></div></div><button class="secondary" data-action="profile">编辑我的名片</button></div>${Hexagon.memberSummary(m)}${stats(m)}<div class="section-heading"><h2>我记下的球</h2><span class="optional">${badge(m)}</span></div><div class="feed">${records.length?records.map(recordCard).join(''):emptyRecord(true)}</div>`;}
function welcome(){app.innerHTML=`<main class="welcome"><div class="welcome-top"><div class="brand"><span class="brand-icon">🎾</span><div><strong>网球搭子</strong><small>COURT NOTES</small></div></div><span class="optional">群里的网球小本本</span></div><div class="welcome-grid"><div class="welcome-copy"><p class="eyebrow">一起打球，也一起记住。</p><h1>你们的搭子。<br>你们的<em>网球故事。</em></h1><p>为微信群开一本共享小本本。每个人自己记球，用自己的头像、昵称，留下这一群人的独特味道。</p><div class="welcome-notes"><div class="welcome-note"><span>01</span><strong>记下日期、时长、搭档和感想</strong></div><div class="welcome-note"><span>02</span><strong>上传头像，拥有自己的球友名片</strong></div><div class="welcome-note"><span>03</span><strong>给搭子鼓掌，收藏只有你们懂的梗</strong></div></div></div><section class="create-card"><h2>给你们的群开一本</h2><form id="create-form" class="form"><div><label for="club-name">群名</label><input id="club-name" name="name" value="网球搭子" maxlength="24" required autocomplete="off"></div><div><label for="club-slogan">群口号 <span class="optional">选填，以后可以改</span></label><input id="club-slogan" name="slogan" placeholder="比如：球可以出界，快乐不能。" maxlength="80"></div><div><label for="founder-name">你的群昵称</label><input id="founder-name" name="nickname" placeholder="搭子们平时怎么叫你？" maxlength="20" required autocomplete="nickname"></div><div class="form-error" role="alert"></div><button class="primary" type="submit">创建群小本本</button><p class="form-helper">创建后复制邀请链接，发到微信群。<br>已有邀请链接？直接从群里点开那条链接。</p></form></section></div><p class="welcome-footer">只有持有邀请链接的人能进入群内容。请把链接留在你们自己的群里。</p></main>`;$('#create-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;await submit(f,async()=>{const v=Object.fromEntries(new FormData(f));const r=await request('/api/clubs','POST',v);state.invite=r.invite;history.replaceState(null,'',`${appBase}#g=${r.invite}`);await load();if(!state.board)throw new Error(state.error);toast('小本本开好了，把搭子们叫进来！');openInvite();});});}
function render(){if(!state.invite){welcome();return;}if(!state.board){app.innerHTML=`<main class="welcome"><div class="brand"><span class="brand-icon">🎾</span><strong>网球搭子</strong></div>${state.error?`<div class="error-panel"><p>${esc(state.error)}</p><button class="secondary" data-action="refresh">重试</button></div><a href="${esc(appBase)}">创建自己的群小本本</a>`:'<p class="loading-line">正在翻开群里的小本本…</p>'}</main>`;return;}const b=state.board,m=me();app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-icon">🎾</span><div><strong>网球搭子</strong><small>COURT NOTES</small></div></div><nav class="side-nav" aria-label="主导航">${nav()}</nav><div class="sidebar-bottom"><div class="side-note"><strong>SEE YOU ON COURT.</strong>我们下次，球场见。</div>${m?.id===b.club.ownerId?'<button class="small-button" data-action="settings">群名和口号</button>':''}<button class="small-button" data-action="invite">${icon('share')}邀请搭子</button></div></aside><main class="main"><header class="topbar"><span class="topbar-date">${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</span><div class="top-actions">${m?.id===b.club.ownerId?'<button class="small-button" data-action="settings">群设置</button>':''}<button class="small-button" data-action="invite">${icon('share')}邀请</button><button class="icon-button" data-action="profile" aria-label="${m?'编辑我的名片':'建立我的名片'}">${avatar(m)}</button></div></header>${state.error?`<div class="error-panel"><p>${esc(state.error)}</p><button class="secondary" data-action="refresh">重试</button></div>`:''}${({feed,members,culture,my:Growth.page}[state.tab]||feed)()}</main><nav class="mobile-nav" aria-label="手机主导航">${nav()}</nav></div>`;}
function modal(title,content,eyebrow='COURT NOTES'){if(dialog.open)dialog.close();$('#dialog-title').textContent=title;$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-body').innerHTML=content;dialog.showModal();dialog.querySelector('input:not([type=hidden]),textarea,button')?.focus();}
$('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
async function submit(form,action){const btn=form.querySelector('button[type=submit]'),error=form.querySelector('.form-error');if(btn.disabled)return;btn.disabled=true;error.textContent='';try{await action();}catch(e){error.textContent=e.message;error.scrollIntoView({block:'nearest'});}finally{btn.disabled=false;}}
function requireMember(){if(!state.board.me){openProfile();return false;}return true;}
function actionButtons(label){return `<div class="form-error" role="alert"></div><div class="form-actions"><button type="button" class="secondary" data-action="close">取消</button><button type="submit" class="primary">${label}</button></div>`;}
function openProfile(){const m=me();modal(m?'我的球友名片':'给自己一张球友名片',`<form id="profile-form" class="form"><div class="avatar-editor">${avatar(m,true)}<div><label for="avatar-file">我的头像 <span class="optional">选填</span></label><input type="file" id="avatar-file" accept="image/*"><p class="form-helper">选择图片后会显示预览。</p></div></div><div><label for="nickname">群昵称</label><input id="nickname" name="nickname" required maxlength="20" value="${esc(m?.nickname||'')}" placeholder="搭子们平时怎么叫你？" autocomplete="nickname"></div><div><label for="bio">我的球场宣言 <span class="optional">选填</span></label><input id="bio" name="bio" value="${esc(m?.bio||'')}" maxlength="80" placeholder="比如：反手还在练，热情已经满格。"></div><p class="profile-help">这个微信或浏览器会记住你的名片。换设备或清除浏览器数据后，需要重新建立名片。</p>${actionButtons(m?'保存名片':'加入这群搭子')}</form>`,'MY PLAYER CARD');let selected=null,preview=null;$('#avatar-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const error=$('#profile-form .form-error'),saveButton=$('#profile-form button[type=submit]');saveButton.disabled=true;try{selected=await avatarBlob(file);if(preview)URL.revokeObjectURL(preview);preview=URL.createObjectURL(selected);$('#profile-form .avatar').innerHTML=`<img src="${preview}" alt="新头像预览">`;error.textContent='';}catch(e){selected=null;error.textContent=e.message;}finally{saveButton.disabled=false;}};$('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await submit(f,async()=>{await request('/api/profile','POST',Object.fromEntries(new FormData(f)));if(selected){const r=await apiFetch('/api/avatar',{method:'POST',headers:{'Content-Type':selected.type},body:selected});if(!r.ok){const result=await r.json();throw new Error(`昵称已保存，头像未上传成功：${result.error}`);}}dialog.close();if(preview)URL.revokeObjectURL(preview);await load();toast(m?'名片更新好了。':'入场了，下一场一起打！');});};}
async function avatarBlob(file){if(file.size>15*1024*1024)throw new Error('这张图片太大了，请选择 15MB 以内的图片。');let image,objectUrl;try{objectUrl=URL.createObjectURL(file);image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=objectUrl;});const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const context=canvas.getContext('2d');const size=Math.min(image.width,image.height);context.fillStyle='#fff';context.fillRect(0,0,512,512);context.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,0,0,512,512);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!blob)throw new Error();return blob;}catch{throw new Error('这张图片打不开，请换一张 JPG、PNG 或 WebP 图片。');}finally{if(objectUrl)URL.revokeObjectURL(objectUrl);}}
function openRecord(recordId,trainingMode=false){if(!requireMember())return;const r=findRecord(recordId);if(recordId&&!r){toast('记录暂时没有加载出来，请刷新后再试。');return;}const formId=r?.id||crypto.randomUUID();modal(r?'修改这次记录':trainingMode?'记录训练':'记一场球',`<form id="record-form" class="form"><div class="row"><div><label for="play-date">打球日期</label><input type="date" id="play-date" name="playDate" value="${r?.play_date||state.board.today||today()}" max="${state.board.today||today()}" required></div><div><label for="minutes">训练 / 打球时长 <span class="optional">分钟</span></label><input type="number" id="minutes" name="minutes" value="${r?.minutes||90}" min="1" max="1440" step="1" required inputmode="numeric"></div></div>${Growth.form(r,trainingMode)}<div><label for="partners">搭档 <span class="optional">选填</span></label><input id="partners" name="partners" value="${esc(r?.partners||'')}" placeholder="和谁一起打的？可以写多个昵称。" maxlength="120" list="partner-list"><datalist id="partner-list">${state.board.members.filter(m=>m.id!==state.board.me).map(m=>`<option value="${esc(m.nickname)}"></option>`).join('')}</datalist></div><div><label for="venue">球场 <span class="optional">选填</span></label><input id="venue" name="venue" maxlength="60" value="${esc(r?.venue||'')}" placeholder="今天在哪儿挥拍？"></div><div><label>今天的状态</label><div class="mood-options">${moods.map((m,i)=>`<label><input type="radio" name="mood" value="${m}" ${(r?.mood||moods[0])===m?'checked':''}>${m}</label>`).join('')}</div></div><div><label for="record-note">打球感想 <span class="optional">选填，500 字以内</span></label><textarea id="record-note" name="note" maxlength="500" placeholder="一记好球、一次进步，或者球场上发生的趣事…">${esc(r?.note||'')}</textarea></div>${Hexagon.form(r)}${actionButtons(r?'保存修改':'记住这场球')}</form>`,'A GOOD DAY ON COURT');Hexagon.bindForm($('#record-form'));Growth.bindForm($('#record-form'));$('#record-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await submit(f,async()=>{const data={...Object.fromEntries(new FormData(f)),id:formId,skills:Hexagon.readForm(f),training:Growth.readTraining(f)};await request(r?`/api/records/${r.id}`:'/api/records',r?'PATCH':'POST',data);dialog.close();Growth.model.page=0;await load();toast(r?'这次记录改好了。':data.training?'训练记下了，下次接着练！':'这场记住了，下次继续！');});};}
function openCulture(){if(!requireMember())return;const id=crypto.randomUUID();modal('留下一句群内梗',`<form id="culture-form" class="form"><p class="subtext">群里的口头禅、球场上的名场面，都值得贴在这面墙上。</p><div><label for="culture-content">只有你们懂的那一句</label><textarea id="culture-content" name="content" maxlength="160" required placeholder="写一句你们群里才懂的梗，最多 160 字。"></textarea></div>${actionButtons('贴到群内梗墙')}</form>`,'ONLY WE GET IT');$('#culture-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await submit(f,async()=>{await request('/api/culture','POST',{...Object.fromEntries(new FormData(f)),id});dialog.close();state.tab='culture';await load();toast('这句梗，留在群里了。');});};}
function openSettings(){const c=state.board.club;if(c.ownerId!==state.board.me)return;modal('群名和口号',`<form id="settings-form" class="form"><div><label for="edit-club-name">群名</label><input id="edit-club-name" name="name" required maxlength="24" value="${esc(c.name)}"></div><div><label for="edit-slogan">群口号 <span class="optional">选填</span></label><textarea id="edit-slogan" name="slogan" maxlength="80" placeholder="写一句属于你们的话。">${esc(c.slogan)}</textarea></div>${actionButtons('保存群设置')}</form>`);$('#settings-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await submit(f,async()=>{await request('/api/club','PATCH',Object.fromEntries(new FormData(f)));dialog.close();await load();toast('现在，更像你们的群了。');});};}
function shareUrl(){return `${appBase}#g=${state.invite}`;}
function openInvite(){modal('叫搭子们进来',`<p>把这条邀请链接发到微信群，大家点开后，就能建立名片、记录打球。</p><textarea class="share-url" id="invite-url" readonly aria-label="群邀请链接">${esc(shareUrl())}</textarea><p class="share-warning">持有链接的人可以进入和加入，请只分享给群里的朋友。微信内可以长按复制链接，或使用右上角菜单分享。</p><div class="form-actions"><button class="primary" data-action="copy-invite">${icon('share')}复制群邀请链接</button>${!remoteApi?'<button class="secondary" data-action="copy-pages-invite">复制 GitHub 邀请链接</button>':''}</div>`,'SEE YOU ON COURT');}
async function copyInvite(url=shareUrl()){const input=$('#invite-url');if(input)input.value=url;try{await navigator.clipboard.writeText(url);toast('邀请链接复制好了，发到微信群吧。');}catch{input.focus();input.select();try{if(document.execCommand('copy'))toast('邀请链接复制好了。');else toast('长按已选中的链接，选择复制。');}catch{toast('长按已选中的链接，选择复制。');}}}
function confirmDelete(type,id){const r=type==='record'?findRecord(id):state.board.culture.find(p=>p.id===id);if(!r)return;modal(type==='record'?'删除这场记录？':'删除这句群内梗？',`<form id="delete-form" class="form"><p>${type==='record'?`${day(r.play_date)} · ${r.minutes} 分钟的打球记录及收到的鼓掌会一起删除。`:'这句话会从群内梗墙移除。'}删除后无法恢复。</p>${actionButtons('确认删除')}</form>`,'ONE LAST CHECK');$('#delete-form').onsubmit=async e=>{e.preventDefault();await submit(e.currentTarget,async()=>{await request(`/api/${type==='record'?'records':'culture'}/${id}`,'DELETE');dialog.close();await load();toast('已删除。');});};}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(action==='link-pages')beginPagesLink();else if(action==='pages-return')location.replace(`${PAGES_BASE}#g=${encodeURIComponent(state.invite)}`);else if(action==='confirm-pages-link'){b.disabled=true;try{const result=await request('/api/pages-session','POST',{});if(!validToken(result.sessionToken))throw new Error('名片连接未完成，请重试。');location.replace(`${PAGES_BASE}#g=${encodeURIComponent(state.invite)}&session=${result.sessionToken}&state=${state.linkIntent}`);}catch(err){toast(err.message);b.disabled=false;}}else if(action==='close')dialog.close();else if(action==='tab'){state.tab=b.dataset.tab;render();loadAvatars();window.scrollTo({top:0});}else if(action==='profile')openProfile();else if(action==='record')openRecord();else if(action==='training')openRecord(undefined,true);else if(action==='checkin'){if(!requireMember())return;b.disabled=true;try{const result=await request('/api/checkins','POST',{});await load();toast(result.alreadyChecked?'今天已经签到啦。':'签到成功，今天又坚持了一点！');}catch(err){toast(err.message);b.disabled=false;}}else if(action==='growth-month'){Growth.model.month=b.dataset.month;b.disabled=true;await Growth.load();render();loadAvatars();}else if(action==='growth-page'){Growth.model.page=Number(b.dataset.page);b.disabled=true;await Growth.load();render();loadAvatars();$('.growth-timeline')?.scrollIntoView({block:'start'});}else if(action==='use-training-plan'){const input=$('#training-content'),plan=Growth.model.data?.nextPlan?.next_plan||'';if(input&&plan){input.value=input.value.trim()?input.value.trim()+'\n'+plan:plan;input.focus();}}else if(action==='edit-record')openRecord(b.dataset.id);else if(action==='view-hex')openHexagon(b.dataset.id);else if(action==='culture')openCulture();else if(action==='settings')openSettings();else if(action==='invite')openInvite();else if(action==='copy-invite')copyInvite();else if(action==='copy-pages-invite')copyInvite(`${PAGES_BASE}#g=${state.invite}`);else if(action==='delete-record')confirmDelete('record',b.dataset.id);else if(action==='delete-culture')confirmDelete('culture',b.dataset.id);else if(action==='refresh'){b.disabled=true;await load();}else if(action==='cheer'){if(!requireMember())return;b.disabled=true;try{await request('/api/cheers','POST',{recordId:b.dataset.id,emoji:b.dataset.emoji});await load();}catch(e){toast(e.message);b.disabled=false;}}});
window.addEventListener('hashchange',()=>{state.invite=new URLSearchParams(location.hash.slice(1)).get('g');if(remoteApi){const token=readSession(state.invite);state.session=validToken(token)?token:null;}state.board=null;state.error=null;state.tab='feed';Growth.reset();render();if(state.invite)load();if(state.linkFailed)toast('名片连接未完成，请重新选择使用原页面的名片。');});
setInterval(()=>{if(state.invite&&state.board&&!dialog.open&&document.visibilityState==='visible')load({quiet:true});},30000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.invite&&!dialog.open)load({quiet:true});});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const [name,tab] of [['view_court_records','feed'],['view_player_cards','members'],['view_group_culture','culture']]){try{Promise.resolve(document.modelContext.registerTool({name,title:tabs.find(t=>t[0]===tab)[1],description:'打开对应的群视图并返回当前共享内容；不创建或修改记录。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('此操作不接受参数。');if(!state.invite)throw new Error('请先通过群邀请链接进入。');await load();if(state.error)throw new Error(state.error);state.tab=tab;render();return {club:state.board.club.name,view:tab,items:tab==='feed'?state.board.records:tab==='members'?state.board.members:state.board.culture};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
function openHexagon(recordId){
  const record=findRecord(recordId),scores=Hexagon.scores(record);
  if(!scores)return;
  modal('这场球的六边形',`<p class="hex-detail-meta">${esc(member(record.member_id)?.nickname||record.nickname)} · ${day(record.play_date)} · ${record.minutes} 分钟</p><div class="hex-detail-chart">${Hexagon.chart(scores,'本场六维自评')}${Hexagon.total(scores)}</div><p class="hex-detail-highlight">${Hexagon.highlight(scores)}</p><p class="hex-explainer">本场自评：1 待加强 · 5 基本到位 · 10 很满意<br>记录当场的感受，每一场都有自己的形状。</p>${record.member_id===state.board.me?`<div class="form-actions"><button class="secondary" data-action="edit-record" data-id="${record.id}">修改这场自评</button></div>`:''}`,'MY SIX-SIDED STORY');
}
document.addEventListener('change',e=>{if(e.target.id==='growth-metric'){Growth.model.metric=e.target.value;render();loadAvatars();}});
render();if(state.invite)load();if(state.linkFailed)toast('名片连接未完成，请重新选择使用原页面的名片。');
