function privateViewGuard(){const epoch=state.epoch,clubId=state.board?.club.id,accountId=state.account?.id;return ()=>epoch===state.epoch&&clubId===state.board?.club.id&&accountId===state.account?.id;}
function openEmailAuth(mode='login'){
  const signup=mode==='signup';
  if(signup&&!state.account&&state.clubs.length){const old=state.clubs[0];modal('先保留你的原名片',`<p>本设备还保有 <strong>${esc(old.nickname)}</strong> 的原名片。先保存原身份，再在“我的账号”设置邮箱和密码，头像、记录和管理员身份会继续保留。</p><div class="form-actions"><button class="primary" data-action="register" data-club="${esc(old.id)}">保存原身份</button><button class="secondary" data-action="recovery-login">用原恢复码登录</button></div>`);return;}
  modal(signup?'注册网球搭子账号':'登录网球搭子',`<form id="email-auth-form" class="form">${signup?'<div><label for="auth-name">昵称</label><input id="auth-name" name="nickname" maxlength="20" autocomplete="nickname" required></div>':''}<div><label for="auth-email">邮箱</label><input id="auth-email" name="email" type="email" maxlength="254" autocomplete="email" required></div><div><label for="auth-password">密码</label><input id="auth-password" name="password" type="password" minlength="10" maxlength="128" autocomplete="${signup?'new-password':'current-password'}" required><p class="form-helper">至少 10 个字符。邮箱仅用于登录，对球友显示昵称。</p></div>${signup?'<p class="form-helper">注册后会提供本人恢复码，用于忘记密码时找回账号。</p>':''}${actionButtons(signup?'注册账号':'登录')}<div class="auth-links"><button type="button" class="text-button" data-action="${signup?'email-login':'email-signup'}">${signup?'已有账号，登录':'没有账号，注册'}</button><button type="button" class="text-button" data-action="recovery-login">用恢复码登录 / 找回密码</button></div></form>`);
  $('#email-auth-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;await submit(form,async()=>{const result=await request(signup?'/api/auth/signup':'/api/auth/login','POST',Object.fromEntries(new FormData(form)));form.elements.password.value='';closeDialog();await finishIdentity(result);if(signup)showRecoveryCode(result.recoveryCode);else toast('登录成功。');});};
}
function openCredentials(){
  if(!state.account){openEmailAuth();return;}
  modal(state.account.hasEmail?'更新登录邮箱和密码':'设置邮箱和密码',`<form id="credentials-form" class="form"><p class="form-helper">保留当前账号的全部名片、照片和历史。恢复码仍可用于找回账号。</p><div><label for="credentials-email">登录邮箱</label><input id="credentials-email" name="email" type="email" maxlength="254" autocomplete="email" required></div><div><label for="credentials-password">新密码</label><input id="credentials-password" name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></div>${actionButtons('保存登录方式')}</form>`);
  $('#credentials-form').onsubmit=async e=>{e.preventDefault();await submit(e.currentTarget,async()=>{await request('/api/auth/credentials','POST',Object.fromEntries(new FormData(e.currentTarget)));closeDialog();await loadAccount();render();toast('邮箱和密码已保存。');});};
}
function renderInviteGate(){
  const club=state.preview.club;document.title=`加入 ${club.name} · 网球搭子`;
  app.innerHTML=`<main class="welcome invite-gate"><div class="brand"><span class="brand-icon">🎾</span><strong>网球搭子</strong></div><section class="create-card"><p class="eyebrow">群邀请</p><h1>${esc(club.name)}</h1>${club.slogan?`<p>${esc(club.slogan)}</p>`:''}<p class="privacy-note">球员卡、打球记录和照片仅小组成员可见。</p>${state.account?`<p>当前账号：<strong>${esc(state.account.displayName)}</strong></p><form id="join-form" class="form"><div><label for="join-name">我的群昵称</label><input id="join-name" name="nickname" value="${esc(accountAlias())}" maxlength="20" required autocomplete="nickname"></div>${actionButtons('加入这群搭子')}</form><button class="text-button" data-action="email-login">切换账号</button>`:'<div class="form-actions"><button class="primary" data-action="email-signup">注册并加入</button><button class="secondary" data-action="email-login">已有账号，登录</button></div><button class="text-button" data-action="recovery-login">用原恢复码登录</button>'}<button class="text-button" data-action="home">返回我的群</button></section></main>`;
  const form=$('#join-form');if(form)form.onsubmit=async e=>{e.preventDefault();await submit(form,async()=>{await request('/api/profile','POST',Object.fromEntries(new FormData(form)));resetView();await loadAccount();await load();toast('已加入，欢迎来记球。');});};
}
function monthlySection(m){
  const rows=Growth.model.data?.monthlyRatings||[],current=m.rating,previous=current?rows.filter(r=>r.month<current.month).at(-1):null;
  const comparison=current&&previous?`<div class="rating-changes">${Hexagon.dimensions.map(d=>{const a=current[d.key],b=previous[d.key],delta=a!==null&&b!==null?a-b:null;return `<span>${d.label}<strong>${delta===null?'暂无可比':delta>0?'+'+delta:String(delta)}</strong></span>`;}).join('')}</div><p class="form-helper">与自己的 ${esc(previous.month)} 月自评比较。</p>`:'<p class="form-helper">积累两个月后，可与自己的上次评分比较。</p>';
  return `<section class="growth-card monthly-card"><div class="section-heading"><h2>我的月度球员卡</h2><button class="secondary" data-action="monthly-rating">更新能力</button></div><p class="privacy-note">${current?`${esc(current.month)} 月自评`:'本月尚未填写'} · 默认仅组内可见</p>${Hexagon.chart(Hexagon.scores(current),'月度能力自评')}${comparison}<div class="form-actions"><button class="text-button" data-action="personal-share">${m.public_shared?'管理公开分享':'分享我的球员卡'}</button></div>${rows.length?`<details class="growth-data"><summary>查看已保存的月份</summary><div class="rating-month-list">${[...rows].reverse().map(r=>`<button class="small-button" data-action="monthly-rating" data-month="${esc(r.month)}">${esc(r.month)}</button>`).join('')}</div></details>`:''}</section>`;
}
async function openMonthlyRatings(month,memberId){
  if(!requireMember())return;const stillCurrent=privateViewGuard();
  let rows=Growth.model.data?.monthlyRatings||[];const target=memberId||state.board.me;
  if(target!==state.board.me){try{rows=(await request(`/api/ratings?memberId=${target}`)).ratings;if(!stillCurrent())return;}catch(e){if(stillCurrent())toast(e.message);return;}}
  const selected=month||state.board.today.slice(0,7),existing=rows.find(r=>r.month===selected);
  modal(target===state.board.me?'更新我的月度能力':'管理员代改月度能力',`<form id="monthly-rating-form" class="form"><div><label for="rating-month">月份</label><input id="rating-month" name="month" type="month" max="${state.board.today.slice(0,7)}" value="${esc(selected)}" required><p class="form-helper">每个月独立保存。待测保留为空，不计成 0 分。</p></div>${Hexagon.dimensions.map(d=>`<div class="rating-select"><label for="rating-${d.key}">${d.label}</label><select id="rating-${d.key}" name="${d.key}"><option value="">待测</option>${Array.from({length:11},(_,n)=>`<option value="${n}" ${existing?.[d.key]===n?'selected':''}>${n} 分</option>`).join('')}</select></div>`).join('')}${target!==state.board.me?'<p class="privacy-note">代改会记录管理员、时间及修改前后的评分。</p>':''}${actionButtons('保存这个月')}</form>`);
  const form=$('#monthly-rating-form');form.elements.month.onchange=()=>{const previous=rows.find(r=>r.month===form.elements.month.value);for(const d of Hexagon.dimensions)form.elements[d.key].value=previous?.[d.key]??'';};
  form.onsubmit=async e=>{e.preventDefault();await submit(form,async()=>{const skills=Object.fromEntries(Hexagon.dimensions.map(d=>[d.key,form.elements[d.key].value===''?null:Number(form.elements[d.key].value)]));await request('/api/ratings','POST',{month:form.elements.month.value,skills,memberId:target});closeDialog();await load();toast('月度能力已保存。');});};
}
function openSharing(){
  if(!requireMember())return;const m=me();
  modal('分享我的球员卡',`<p>公开内容仅包括你的头像、昵称、介绍和最新月度自评。打球记录、训练照片和其他球友的资料仍仅组内可见。</p><p class="privacy-note">当前：${m.public_shared?'已公开分享':'仅组内可见'}</p><div id="public-link-result"></div><div class="form-actions"><button class="primary" data-action="enable-share">${m.public_shared?'生成新的公开链接':'创建公开链接'}</button>${m.public_shared?'<button class="secondary" data-action="disable-share">撤回公开分享</button>':''}</div><p class="form-helper">生成新链接会使旧公开链接失效。</p>`);
}
async function changeSharing(enabled,button){
  button.disabled=true;try{const result=await request('/api/share','POST',{enabled});if(enabled){const url=`${appBase}#p=${result.token}`;$('#public-link-result').innerHTML=`<label for="public-card-url">公开球员卡链接</label><textarea id="public-card-url" class="share-url" readonly>${esc(url)}</textarea><button class="secondary" data-action="copy-public">复制公开链接</button>`;if(me())me().public_shared=1;button.textContent='生成新的公开链接';if(!$('#dialog-body [data-action="disable-share"]'))$('#dialog-body .form-actions').insertAdjacentHTML('beforeend','<button class="secondary" data-action="disable-share">撤回公开分享</button>');}else{closeDialog();await load();toast('公开分享已撤回，旧链接已失效。');}}catch(e){toast(e.message);}finally{button.disabled=false;}
}
async function loadPublicCard(){
  const token=state.publicToken,epoch=state.epoch;state.publicCard=null;state.publicError=null;renderPublicCard();
  try{const response=await fetch(new URL(`/api/public/card/${token}`,apiBase),{credentials:'omit',cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'公开球员卡无法打开。');if(token!==state.publicToken||epoch!==state.epoch)return;state.publicCard=data;renderPublicCard();if(data.hasAvatar){const r=await fetch(new URL(`/api/public/avatar/${token}`,apiBase),{credentials:'omit',cache:'no-store'});if(r.ok){const blob=await r.blob();if(token!==state.publicToken||epoch!==state.epoch)return;const url=URL.createObjectURL(blob);state.avatars.set('public',{url});const image=$('#public-player-avatar');if(image)image.src=url;}}}catch(e){if(token===state.publicToken&&epoch===state.epoch){state.publicError=e.message;renderPublicCard();}}
}
function renderPublicCard(){
  document.title='网球搭子 · 公开球员卡';const p=state.publicCard;
  app.innerHTML=`<main class="welcome public-card-page"><div class="brand"><span class="brand-icon">🎾</span><strong>网球搭子</strong></div>${state.publicError?`<div class="error-panel"><p>${esc(state.publicError)}</p></div>`:p?`<article class="member-card"><p class="eyebrow">本人公开的球员卡</p>${p.hasAvatar?'<img id="public-player-avatar" class="public-avatar" alt="球员头像">':''}<h1>${esc(p.nickname)}</h1><p class="bio">${esc(p.bio||'下一场，球场见。')}</p>${Hexagon.chart(Hexagon.scores(p.rating),'本人公开的月度能力')}<p class="privacy-note">${p.rating?esc(p.rating.month)+' 月自评':'月度能力待测'}</p></article>`:'<p class="loading-line">正在打开球员卡…</p>'}<button class="secondary" data-action="home">我的群</button></main>`;
}
function recordPhotoGallery(record){
  const items=(state.board?.photos||[]).filter(p=>p.record_id===record.id),canEdit=record.member_id===state.board?.me,canDelete=canEdit||state.board?.me===state.board?.club.ownerId;
  return `${items.length?`<div class="record-photos">${items.map(p=>`<figure><button class="photo-open" data-action="view-photo" data-photo="${p.id}" aria-label="查看打球照片"><img data-photo-id="${p.id}" alt="${esc(record.nickname||'球友')}的打球照片" loading="lazy"></button>${canDelete?`<button class="text-button danger" data-action="delete-photo" data-photo="${p.id}">删除照片</button>`:''}</figure>`).join('')}</div>`:''}${canEdit&&items.length<3?`<button class="text-button photo-add" data-action="add-photos" data-record="${record.id}">添加打球照片</button>`:''}`;
}
async function loadRecordPhotos(){
  const epoch=state.epoch;for(const img of document.querySelectorAll('img[data-photo-id]')){const photoId=img.dataset.photoId,key='photo:'+photoId,cached=state.avatars.get(key);if(cached){img.src=cached.url;continue;}try{const response=await apiFetch('/api/photos/'+photoId);if(!response.ok)continue;const blob=await response.blob();if(epoch!==state.epoch)return;const url=URL.createObjectURL(blob);state.avatars.set(key,{url});for(const image of document.querySelectorAll(`img[data-photo-id="${photoId}"]`))image.src=url;}catch{}}
}
async function photoBlob(file){
  if(file.size>15*1024*1024)throw new Error('照片请小于 15MB。');const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=url;}),scale=Math.min(1,1600/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const context=canvas.getContext('2d');context.fillStyle='white';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.85));if(!blob||blob.size>2*1024*1024)throw new Error();return blob;}catch{throw new Error('这张照片无法保存，请选择其他 JPG、PNG 或 WebP 图片。');}finally{URL.revokeObjectURL(url);}
}
function openPhotoUpload(recordId){
  const record=findRecord(recordId);if(!record||record.member_id!==state.board.me)return;
  modal('添加打球照片',`<form id="photos-form" class="form"><p class="privacy-note">照片仅组内可见，每场最多 3 张。</p><div><label for="record-photo-files">选择照片</label><input id="record-photo-files" type="file" accept="image/jpeg,image/png,image/webp" multiple required></div>${actionButtons('上传照片')}</form>`);
  const form=$('#photos-form');form.onsubmit=async e=>{e.preventDefault();await submit(form,async()=>{const files=[...$('#record-photo-files').files],existing=(state.board.photos||[]).filter(p=>p.record_id===recordId).length;if(files.length+existing>3)throw new Error(`这场还可以添加 ${3-existing} 张照片。`);let uploaded=0;for(const file of files){try{const blob=await photoBlob(file),response=await apiFetch(`/api/records/${recordId}/photos`,{method:'POST',headers:{'Content-Type':blob.type},body:blob});if(!response.ok){const result=await response.json();throw new Error(result.error||'上传失败');}uploaded++;}catch(e){await load();throw new Error(`${uploaded} 张已保存；剩余照片未上传：${e.message}`);}}closeDialog();await load();toast('打球照片已保存。');});};
}
async function openManagement(){
  if(!state.board||state.board.me!==state.board.club.ownerId)return;const stillCurrent=privateViewGuard();
  try{const data=await request('/api/admin');if(!stillCurrent())return;const actions={'create-invite':'生成邀请','revoke-invite':'撤销邀请','remove-member':'移除成员','restore-member':'恢复成员','edit-profile':'代改名片','edit-rating':'代改评分','delete-record':'移除记录','delete-photo':'移除照片','export-backup':'导出备份'};state.management=data;
    modal('管理小组',`<div class="management-actions"><button class="secondary" data-action="settings">群名和口号</button><button class="primary" data-action="invite">生成邀请</button><button class="secondary" data-action="export-backup">下载完整备份（含照片）</button></div><h3>成员</h3><div class="management-list">${data.members.map(m=>`<div><span><strong>${esc(m.nickname)}</strong><small>${m.removed_at?'已移除':m.id===state.board.club.ownerId?'管理员':'小组成员'}</small></span>${m.id!==state.board.club.ownerId?`<div><button class="text-button" data-action="admin-profile" data-member="${m.id}">代改名片</button><button class="text-button" data-action="admin-rating" data-member="${m.id}">代改评分</button><button class="text-button ${m.removed_at?'':'danger'}" data-action="${m.removed_at?'restore-member':'remove-member'}" data-member="${m.id}">${m.removed_at?'恢复成员':'移除成员'}</button></div>`:''}</div>`).join('')}</div><h3>邀请</h3><div class="management-list">${data.invites.map((v,i)=>`<div><span><strong>${v.id==='original'?'原始群邀请':'群邀请 '+i}</strong><small>${v.revoked_at?'已撤销':v.expires_at&&v.expires_at<=Date.now()?'已过期':v.expires_at?'有效至 '+new Date(v.expires_at).toLocaleDateString('zh-CN'):'长期有效'}</small></span>${!v.revoked_at?`<button class="text-button danger" data-action="revoke-invite" data-invite="${v.id}">撤销</button>`:''}</div>`).join('')}</div><details class="growth-data"><summary>管理操作记录</summary>${data.events.length?data.events.map(v=>`<p class="audit-line">${esc(v.actor)} · ${esc(actions[v.action]||v.action)}<small>${esc(new Date(v.created_at).toLocaleString('zh-CN'))}</small></p>`).join(''):'<p>还没有管理操作。</p>'}</details>`);
  }catch(e){if(stillCurrent())toast(e.message);}
}
function confirmMemberAction(memberId,restore=false){const stillCurrent=privateViewGuard();const m=state.management?.members.find(x=>x.id===memberId);if(!m)return;modal(restore?'恢复这位成员？':'移除这位成员？',`<form id="member-action-form" class="form"><p>${esc(m.nickname)} ${restore?'将恢复组内访问和编辑本人记录的权限。':'将失去组内访问权限，已登录设备也会被拒绝。历史记录会保留。'}</p>${actionButtons(restore?'恢复成员':'确认移除')}</form>`);$('#member-action-form').onsubmit=async e=>{e.preventDefault();await submit(e.currentTarget,async()=>{await request('/api/members/'+memberId,restore?'PATCH':'DELETE',restore?{}:undefined);if(!stillCurrent())return;await load();if(stillCurrent())await openManagement();});};}
function openAdminProfile(memberId){const stillCurrent=privateViewGuard();const m=state.management?.members.find(x=>x.id===memberId);if(!m)return;modal('管理员代改名片',`<form id="admin-profile-form" class="form"><div><label for="admin-name">群昵称</label><input id="admin-name" name="nickname" maxlength="20" value="${esc(m.nickname)}" required></div><div><label for="admin-bio">介绍</label><input id="admin-bio" name="bio" maxlength="80" value="${esc(m.bio)}"></div><p class="privacy-note">保留操作者、时间和修改前后的内容。</p>${actionButtons('保存并记录修改')}</form>`);$('#admin-profile-form').onsubmit=async e=>{e.preventDefault();await submit(e.currentTarget,async()=>{await request(`/api/members/${memberId}/profile`,'POST',Object.fromEntries(new FormData(e.currentTarget)));if(!stillCurrent())return;await load();if(stillCurrent())await openManagement();});};}
async function exportBackup(button){button.disabled=true;try{const response=await apiFetch('/api/export');if(!response.ok){const data=await response.json();throw new Error(data.error||'备份下载失败');}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`网球搭子备份-${state.board.today}.ndjson`;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('完整备份已下载，包含月度历史和照片。');}catch(e){toast(e.message);}finally{button.disabled=false;}}
document.addEventListener('click',async e=>{
  const button=e.target.closest('[data-action]');if(!button||button.disabled)return;const action=button.dataset.action;
  if(action==='email-login')openEmailAuth('login');
  else if(action==='email-signup')openEmailAuth('signup');
  else if(action==='recovery-login')openRecoveryLogin();
  else if(action==='credentials')openCredentials();
  else if(action==='monthly-rating')await openMonthlyRatings(button.dataset.month);
  else if(action==='personal-share')openSharing();
  else if(action==='enable-share'||action==='disable-share')await changeSharing(action==='enable-share',button);
  else if(action==='copy-public'){const input=$('#public-card-url');try{await navigator.clipboard.writeText(input.value);toast('公开球员卡链接已复制。');}catch{input.select();toast('长按选中的链接复制。');}}
  else if(action==='add-photos')openPhotoUpload(button.dataset.record);
  else if(action==='view-photo'){const item=state.avatars.get('photo:'+button.dataset.photo);if(item)modal('球场照片',`<img class="photo-full" src="${item.url}" alt="打球照片">`);}
  else if(action==='delete-photo'){const photoId=button.dataset.photo;modal('删除这张照片？',`<form id="delete-photo-form" class="form"><p>删除后无法恢复。</p>${actionButtons('确认删除')}</form>`);$('#delete-photo-form').onsubmit=async event=>{event.preventDefault();await submit(event.currentTarget,async()=>{await request('/api/photos/'+photoId,'DELETE');closeDialog();await load();toast('照片已删除。');});};}
  else if(action==='management')await openManagement();
  else if(action==='export-backup')await exportBackup(button);
  else if(action==='remove-member'||action==='restore-member')confirmMemberAction(button.dataset.member,action==='restore-member');
  else if(action==='admin-profile')openAdminProfile(button.dataset.member);
  else if(action==='admin-rating')await openMonthlyRatings(undefined,button.dataset.member);
  else if(action==='revoke-invite'){const stillCurrent=privateViewGuard();const inviteId=button.dataset.invite;modal('撤销这条邀请？',`<form id="revoke-invite-form" class="form"><p>这条链接将不能再用于加入小组。已加入成员仍可从“我的群”进入。</p>${actionButtons('确认撤销')}</form>`);$('#revoke-invite-form').onsubmit=async event=>{event.preventDefault();await submit(event.currentTarget,async()=>{const clubId=state.board.club.id;await request('/api/invites/'+inviteId,'DELETE');if(!stillCurrent())return;state.invite=null;state.club=clubId;state.shareInvite=null;history.replaceState(null,'',`${appBase}#c=${clubId}`);await load();if(stillCurrent())await openManagement();});};}
});
